### PR TITLE
feat: add option '--no-install' to skip node modules & pods installation

### PR DESCRIPTION
**Pull request by gabrielmoreira**
**Why?**
I would like to control exactly when dependencies will be installed. (e.g. implement a 'clean' npm script)

**How?**
My proposal is to add a '--no-install' option to prevent npm/yarn/* install & pod install from running.

For a simple implementation, I'm using the prefix '--no-<option>' which automatically sets the value to true in case this option is not informed in the command line.

From `github.com/tj/commander.js`:
> [**Other option types, negatable boolean and boolean|value**](https://github.com/tj/commander.js#user-content-other-option-types-negatable-boolean-and-booleanvalue)
> You can define a boolean option long name with a leading no- to set the option value to false when used. Defined alone this also makes the option true by default.

### CODE REVIEW

**Comment by gabrielmoreira** [comment]
Hi @taboulot 
Any improvement suggestion? Could you merge & publish it?

**Comment by gh-clement-taboulot** [comment]
@gabrielmoreira Thanks for your suggestion !

Going to take a look on it this week.

**Comment by gh-clement-taboulot** [comment]
@gabrielmoreira 

It's perfect ! Going to relesase it.
Thank you !

**Comment by gh-clement-taboulot** [comment]
@gabrielmoreira 

It's perfect ! Going to relesase it.
Thank you !

**Pull request merged**
